---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: exampleSite/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: exampleSite/content/search
  label: Search
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/our-features
  label: Our features
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/faq
  label: Faq
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/contact
  label: Contact
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/changelog
  label: Changelog
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/basic-startup
  label: Basic startup
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/account-bill
  label: Account bill
  create: all
  match: "**/*"
upload_dir: exampleSite/static
public_path: "/static"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
